# -*- coding: utf-8 -*-
"""Unjumbler.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sC_2fHU4ZsRmwvAV3HKm2xEuoEba9CCl
"""

!pip install pyenchant

!apt-get update  # Update the package list to ensure you have the latest information.
!apt-get install libenchant-2-dev # Install the 'enchant' C library development package

#Importing Libraries
from itertools import permutations
import enchant
import nltk
from nltk.corpus import wordnet

#Function to generate valid words
d = enchant.Dict("en_US")
def generate_valid_words(word, valid_words):
  for perm in permutations(word):
      perm_word = ''.join(perm)  # Convert tuple to string

      # Check the condition
      if d.check(perm_word):
        valid_words.append(perm_word)

#Function to print Unjumbeled word with its meaning
def print_Unjumbeled_word(valid_words):
  for word in valid_words:
    print(f"\nThe unjumbeled word is '{word}'\n")
    synsets = wordnet.synsets(word)

    # Print the definitions of the word
    print(f"Definitions for '{word}':")
    for syn in synsets:
        print(f"- {syn.definition()}")

w=input("Enter the Jumbeled word: ")
valid_words=[]
generate_valid_words(w.upper(), valid_words)
print(valid_words)
if len(valid_words)==0:
  print("No valid words found")
else:
  print_Unjumbeled_word(valid_words)